ALTER TABLE unidades_estoque
ADD COLUMN endereco_id BIGINT,
ADD COLUMN descricao TEXT;

ALTER TABLE depositos
ADD COLUMN permite_entrada BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN permite_saida BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN permite_transferencia BOOLEAN NOT NULL DEFAULT TRUE;
