ALTER TABLE categorias_produto
ADD COLUMN descricao TEXT,
ADD COLUMN ativo BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE marcas
ADD COLUMN site VARCHAR(500),
ADD COLUMN contato VARCHAR(160),
ADD COLUMN observacoes TEXT;

ALTER TABLE fornecedores
ADD COLUMN endereco VARCHAR(220),
ADD COLUMN cidade VARCHAR(120),
ADD COLUMN estado VARCHAR(2),
ADD COLUMN site VARCHAR(500),
ADD COLUMN observacoes TEXT;

ALTER TABLE unidades_medida
ADD COLUMN description TEXT,
ADD COLUMN phone VARCHAR(30),
ADD COLUMN email VARCHAR(180),
ADD COLUMN address VARCHAR(220),
ADD COLUMN city VARCHAR(120),
ADD COLUMN state VARCHAR(2),
ADD COLUMN website VARCHAR(500),
ADD COLUMN notes TEXT;

ALTER TABLE tipos_produto
ADD COLUMN description TEXT,
ADD COLUMN phone VARCHAR(30),
ADD COLUMN email VARCHAR(180),
ADD COLUMN address VARCHAR(220),
ADD COLUMN city VARCHAR(120),
ADD COLUMN state VARCHAR(2),
ADD COLUMN website VARCHAR(500),
ADD COLUMN notes TEXT;

ALTER TABLE depositos
ADD COLUMN description TEXT,
ADD COLUMN phone VARCHAR(30),
ADD COLUMN email VARCHAR(180),
ADD COLUMN address VARCHAR(220),
ADD COLUMN city VARCHAR(120),
ADD COLUMN state VARCHAR(2),
ADD COLUMN website VARCHAR(500),
ADD COLUMN notes TEXT;

ALTER TABLE fabricantes
ADD COLUMN description TEXT,
ADD COLUMN phone VARCHAR(30),
ADD COLUMN email VARCHAR(180),
ADD COLUMN address VARCHAR(220),
ADD COLUMN city VARCHAR(120),
ADD COLUMN state VARCHAR(2),
ADD COLUMN website VARCHAR(500),
ADD COLUMN notes TEXT;

ALTER TABLE modelos_produto
ADD COLUMN description TEXT,
ADD COLUMN phone VARCHAR(30),
ADD COLUMN email VARCHAR(180),
ADD COLUMN address VARCHAR(220),
ADD COLUMN city VARCHAR(120),
ADD COLUMN state VARCHAR(2),
ADD COLUMN website VARCHAR(500),
ADD COLUMN notes TEXT;

ALTER TABLE materiais
ADD COLUMN description TEXT,
ADD COLUMN phone VARCHAR(30),
ADD COLUMN email VARCHAR(180),
ADD COLUMN address VARCHAR(220),
ADD COLUMN city VARCHAR(120),
ADD COLUMN state VARCHAR(2),
ADD COLUMN website VARCHAR(500),
ADD COLUMN notes TEXT;

ALTER TABLE acabamentos
ADD COLUMN description TEXT,
ADD COLUMN phone VARCHAR(30),
ADD COLUMN email VARCHAR(180),
ADD COLUMN address VARCHAR(220),
ADD COLUMN city VARCHAR(120),
ADD COLUMN state VARCHAR(2),
ADD COLUMN website VARCHAR(500),
ADD COLUMN notes TEXT;
