"use client";

import { useEffect, useState, useTransition } from "react";
import { Modal } from "@/components/ui/modal";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { createProductReference, getProductReference, listProductReferences, updateProductReference } from "@/lib/estoque/product-references";
import type { LookupKind, LookupRecord } from "../produto/lookup/lookup-types";

const empty = { description:"", documentNumber:"", phone:"", email:"", address:"", city:"", state:"", website:"", notes:"", active:true, parentCategoryId:"", seoDescription:"", coverImage:"", level:"1", displayOrder:"", batchControlled:false, expirationControlled:false, serialControlled:false, allowNegativeStock:false, defaultMinimumStock:"", defaultMaximumStock:"", defaultSafetyStock:"", defaultIssueMethod:"", inactiveDays:"", externalCode:"", automaticId:true, requestedId:"", automaticCode:true, shortName:"", manufacturerId:"", logoUrl:"", unitSymbol:"", unitType:"OUTRO", decimalPlaces:"0", baseUnitId:"", conversionFactor:"1.000000", physicalProduct:true, stockControlled:true, purchaseAllowed:true, saleAllowed:true, batchControl:false, expirationControl:false, serialControl:false, fiscalItemTypeCode:"" };

export function ProductReferenceFormModal({ kind, label, record, onClose, onSaved }: { kind: LookupKind; label: string; record?: LookupRecord | null; onClose:()=>void; onSaved:()=>void }) {
  const [name,setName]=useState(record?.name||""); const [code,setCode]=useState(record && record.value!==record.name?record.value:"");
  const [details,setDetails]=useState(empty); const [error,setError]=useState(""); const [pending,startTransition]=useTransition();
  const [categories,setCategories]=useState<LookupRecord[]>([]);
  const [manufacturers,setManufacturers]=useState<LookupRecord[]>([]);
  const [units,setUnits]=useState<LookupRecord[]>([]);
  const usesCode=["category","brand","unit","type","warehouse","manufacturer","model","material","finish"].includes(kind);
  const hasContact=["brand","supplier","warehouse","manufacturer"].includes(kind);
  const hasAddress=["supplier","warehouse","manufacturer"].includes(kind);
  const hasWebsite=["brand","supplier","manufacturer"].includes(kind);
  const hasNotes=kind!=="category"&&kind!=="unit"&&kind!=="type";
  const isExtended=hasContact||hasAddress||hasWebsite||hasNotes;
  const set=(key:keyof typeof empty,value:string|boolean)=>setDetails((current)=>({...current,[key]:value}));
  useEffect(()=>{if(kind==="category")void listProductReferences("category").then(setCategories);if(kind==="brand")void listProductReferences("manufacturer").then(setManufacturers);if(kind==="unit")void listProductReferences("unit").then(setUnits);if(!record)return; getProductReference(kind,record.id).then((data)=>{setName(String(data.name||""));setCode(String(data.code||""));setDetails({...empty,description:String(data.description||""),documentNumber:String(data.document_number||""),phone:String(data.phone||""),email:String(data.email||""),address:String(data.address||""),city:String(data.city||""),state:String(data.state||""),website:String(data.website||""),notes:String(data.notes||""),active:data.active!==false,parentCategoryId:String(data.parent_category_id||""),seoDescription:String(data.seo_description||""),coverImage:String(data.cover_image||""),level:String(data.nivel||1),displayOrder:String(data.ordem_exibicao||""),batchControlled:data.controla_lote===true,expirationControlled:data.controla_validade===true,serialControlled:data.controla_serie===true,allowNegativeStock:data.permite_estoque_negativo===true,defaultMinimumStock:String(data.estoque_minimo_padrao||""),defaultMaximumStock:String(data.estoque_maximo_padrao||""),defaultSafetyStock:String(data.estoque_seguranca_padrao||""),defaultIssueMethod:String(data.metodo_saida_padrao||""),inactiveDays:String(data.dias_sem_movimento||""),externalCode:String(data.external_code||data.codigo_externo||""),shortName:String(data.short_name||""),manufacturerId:String(data.manufacturer_id||""),logoUrl:String(data.logo_url||""),unitSymbol:String(data.unit_symbol||""),unitType:String(data.unit_type||"OUTRO"),decimalPlaces:String(data.decimal_places??0),baseUnitId:String(data.base_unit_id||""),conversionFactor:String(data.conversion_factor||"1.000000"),physicalProduct:data.physical_product!==false,stockControlled:data.stock_controlled!==false,purchaseAllowed:data.purchase_allowed!==false,saleAllowed:data.sale_allowed!==false,batchControl:data.batch_control===true,expirationControl:data.expiration_control===true,serialControl:data.serial_control===true,fiscalItemTypeCode:String(data.fiscal_item_type_code||"")});}).catch(()=>setError("Não foi possível carregar o cadastro."));},[kind,record]);
  return <Modal open title={`${record?"Editar":"Cadastrar"} ${label}`} width={kind==="category"?"max-w-5xl":isExtended?"max-w-4xl":"max-w-2xl"} height={kind==="category"?"h-[90vh]":isExtended?"h-[82vh]":undefined} onClose={onClose}>
    <div className="grid gap-3 sm:grid-cols-2">
      {kind==="category"&&!record&&<div className="sm:col-span-2 grid gap-3 sm:grid-cols-[180px_1fr]"><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={details.automaticId} onChange={(e)=>set("automaticId",e.target.checked)}/>Gerar ID automaticamente</label><Input type="number" min="1" disabled={details.automaticId} value={details.requestedId} onChange={(e)=>set("requestedId",e.target.value)} placeholder={details.automaticId?"ID será gerado automaticamente":"Informe o ID"}/></div>}
      {kind==="category"&&!record&&<label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={details.automaticCode} onChange={(e)=>set("automaticCode",e.target.checked)}/>Gerar código automaticamente</label>}
      <label className="space-y-1 text-sm font-semibold"><span>{kind==="category"?"Nome da categoria":["unit","type"].includes(kind)?"Nome":"Nome / descrição"}</span><Input value={name} onChange={(e)=>setName(e.target.value)} placeholder={kind==="category"?"Nome da categoria":["unit","type"].includes(kind)?"Nome":"Nome / descrição"}/></label>
      {usesCode&&<label className="space-y-1 text-sm font-semibold"><span>Código</span><Input disabled={kind==="category"&&!record&&details.automaticCode} value={code} onChange={(e)=>setCode(e.target.value)} placeholder={kind==="category"&&details.automaticCode?"Código será gerado automaticamente":kind==="unit"?"UN":kind==="brand"?"MAR-001":"Código"}/></label>}
      {kind==="brand"&&<><Input value={details.shortName} onChange={(e)=>set("shortName",e.target.value)} placeholder="Nome reduzido"/><select className="input" value={details.manufacturerId} onChange={(e)=>set("manufacturerId",e.target.value)}><option value="">Sem fabricante vinculado</option>{manufacturers.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select><Input value={details.externalCode} onChange={(e)=>set("externalCode",e.target.value)} placeholder="Código externo / integração"/><div className="space-y-1"><label className="text-sm font-semibold">Logo / imagem</label><Input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event)=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>set("logoUrl",String(reader.result));reader.readAsDataURL(file);}}/></div></>}
      {kind==="unit"&&<><label className="space-y-1 text-sm font-semibold"><span>Sigla</span><Input value={details.unitSymbol} maxLength={10} onChange={(e)=>set("unitSymbol",e.target.value.toUpperCase())} placeholder="UN"/></label><label className="space-y-1 text-sm font-semibold"><span>Tipo</span><select className="input w-full" value={details.unitType} onChange={(e)=>set("unitType",e.target.value)}><option value="UNIDADE">Unidade</option><option value="PESO">Peso</option><option value="VOLUME">Volume</option><option value="COMPRIMENTO">Comprimento</option><option value="AREA">Área</option><option value="EMBALAGEM">Embalagem</option><option value="OUTRO">Outro</option></select></label><label className="space-y-1 text-sm font-semibold"><span>Casas decimais</span><Input type="number" min="0" max="6" value={details.decimalPlaces} onChange={(e)=>set("decimalPlaces",e.target.value)} placeholder="0"/></label></>}
      {kind==="unit"&&<><label className="space-y-1 text-sm font-semibold"><span>Unidade base/referência</span><select className="input w-full" value={details.baseUnitId} onChange={(e)=>{set("baseUnitId",e.target.value);if(!e.target.value)set("conversionFactor","1.000000");}}><option value="">Ela mesma</option>{units.filter((item)=>item.id!==record?.id).map((item)=><option key={item.id} value={item.id}>{item.name} - {item.value}</option>)}</select></label><label className="space-y-1 text-sm font-semibold"><span>Fator de conversão</span><Input type="number" min="0.000001" step="0.000001" disabled={!details.baseUnitId} value={details.conversionFactor} onChange={(e)=>set("conversionFactor",e.target.value)} placeholder="1.000000"/></label></>}
      {kind==="type"&&<><label className="space-y-1 text-sm font-semibold sm:col-span-2"><span>Descrição</span><Textarea rows={3} value={details.description} onChange={(e)=>set("description",e.target.value)} placeholder="Descrição do comportamento operacional..."/></label><div className="grid gap-3 sm:col-span-2 sm:grid-cols-2 lg:grid-cols-4">{[["physicalProduct","Produto físico"],["stockControlled","Controla estoque"],["purchaseAllowed","Permite compra"],["saleAllowed","Permite venda"],["batchControl","Controla lote"],["expirationControl","Controla validade"],["serialControl","Controla número de série"]].map(([key,text])=><label key={key} className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={Boolean(details[key as keyof typeof details])} onChange={(e)=>set(key as keyof typeof details,e.target.checked)}/>{text}</label>)}</div><label className="space-y-1 text-sm font-semibold sm:col-span-2"><span>Código do tipo fiscal/SPED</span><Input value={details.fiscalItemTypeCode} onChange={(e)=>set("fiscalItemTypeCode",e.target.value.toUpperCase())} placeholder="Opcional"/></label></>}
      {kind==="category"&&<select className="input" value={details.parentCategoryId} onChange={(e)=>set("parentCategoryId",e.target.value)}><option value="">Sem categoria pai</option>{categories.filter((item)=>item.id!==record?.id).map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select>}
      {kind==="category"&&<><Input value={details.description||""} onChange={(e)=>set("description",e.target.value)} placeholder="Descrição"/><Input readOnly value={`Nível ${details.level||"1"}`} placeholder="Nível automático"/><Input type="number" min="0" value={details.displayOrder||""} onChange={(e)=>set("displayOrder",e.target.value)} placeholder="Ordem de exibição"/><Input value={details.externalCode||""} onChange={(e)=>set("externalCode",e.target.value)} placeholder="Código externo / integração"/></>}
      {kind==="category"&&<Textarea className="sm:col-span-2" rows={3} maxLength={320} value={details.seoDescription} onChange={(e)=>set("seoDescription",e.target.value)} placeholder="Descrição para SEO"/>}
      {kind==="category"&&<div className="sm:col-span-2 space-y-2"><label className="text-sm font-semibold">Imagem de capa</label><Input type="file" accept="image/png,image/jpeg,image/webp" onChange={(event)=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>set("coverImage",String(reader.result));reader.readAsDataURL(file);}}/>{details.coverImage&&<img src={details.coverImage} alt="Capa da categoria" className="h-32 w-full rounded-xl object-cover"/>}</div>}
      {kind==="unit"&&<label className="space-y-1 text-sm font-semibold sm:col-span-2"><span>Descrição</span><Textarea rows={3} value={details.description} onChange={(e)=>set("description",e.target.value)} placeholder="Descrição completa..."/></label>}
      {kind!=="category"&&kind!=="unit"&&kind!=="type"&&<Textarea className="sm:col-span-2" rows={3} value={details.description} onChange={(e)=>set("description",e.target.value)} placeholder="Descrição completa"/>}
      {kind==="category"&&<><div className="sm:col-span-2 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={details.batchControlled} onChange={(e)=>set("batchControlled",e.target.checked)}/>Controla lote</label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={details.expirationControlled} onChange={(e)=>set("expirationControlled",e.target.checked)}/>Controla validade</label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={details.serialControlled} onChange={(e)=>set("serialControlled",e.target.checked)}/>Controla número de série</label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={details.allowNegativeStock} onChange={(e)=>set("allowNegativeStock",e.target.checked)}/>Permite estoque negativo</label></div><Input type="number" min="0" step="0.001" value={details.defaultMinimumStock} onChange={(e)=>set("defaultMinimumStock",e.target.value)} placeholder="Estoque mínimo padrão"/><Input type="number" min="0" step="0.001" value={details.defaultMaximumStock} onChange={(e)=>set("defaultMaximumStock",e.target.value)} placeholder="Estoque máximo padrão"/><Input type="number" min="0" step="0.001" value={details.defaultSafetyStock} onChange={(e)=>set("defaultSafetyStock",e.target.value)} placeholder="Estoque de segurança padrão"/><select className="input" value={details.defaultIssueMethod} onChange={(e)=>set("defaultIssueMethod",e.target.value)}><option value="">Método de saída padrão</option><option value="FIFO">FIFO</option><option value="FEFO">FEFO</option></select><Input type="number" min="0" value={details.inactiveDays} onChange={(e)=>set("inactiveDays",e.target.value)} placeholder="Dias sem movimento"/><Textarea className="sm:col-span-2" rows={3} value={details.notes} onChange={(e)=>set("notes",e.target.value)} placeholder="Observações"/><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={details.active} onChange={(e)=>set("active",e.target.checked)}/>Categoria ativa</label></>}
      {kind==="supplier"&&<Input value={details.documentNumber} onChange={(e)=>set("documentNumber",e.target.value)} placeholder="CPF / CNPJ"/>}
      {hasContact&&<Input value={details.phone} onChange={(e)=>set("phone",e.target.value)} placeholder="Telefone / contato"/>}
      {hasContact&&kind!=="brand"&&<Input type="email" value={details.email} onChange={(e)=>set("email",e.target.value)} placeholder="E-mail"/>}
      {hasAddress&&<><Input value={details.address} onChange={(e)=>set("address",e.target.value)} placeholder="Endereço"/><Input value={details.city} onChange={(e)=>set("city",e.target.value)} placeholder="Cidade"/><Input maxLength={2} value={details.state} onChange={(e)=>set("state",e.target.value.toUpperCase())} placeholder="UF"/></>}
      {hasWebsite&&<Input type="url" value={details.website} onChange={(e)=>set("website",e.target.value)} placeholder="Site"/>}
      {hasNotes&&<Textarea className="sm:col-span-2" rows={3} value={details.notes} onChange={(e)=>set("notes",e.target.value)} placeholder="Observações"/>}
      {kind!=="category"&&<label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={details.active} onChange={(e)=>set("active",e.target.checked)}/>Registro ativo</label>}
      {error&&<p className="text-sm font-semibold text-coral-500">{error}</p>}
      <Button className="sticky bottom-0 sm:col-span-2" variant="primary" disabled={pending||!name.trim()||(usesCode&&!code.trim()&&!(kind==="category"&&!record&&details.automaticCode))||(kind==="unit"&&!details.unitSymbol.trim())||(kind==="category"&&!record&&!details.automaticId&&!details.requestedId)} onClick={()=>startTransition(async()=>{try{setError("");if(record)await updateProductReference(kind,record.id,name,code,details);else await createProductReference(kind,name,code,details);onSaved();}catch(cause){setError(cause instanceof Error?cause.message:"Não foi possível salvar.");}})}>{pending?"Salvando...":record?"Salvar alterações":"Cadastrar"}</Button>
    </div>
  </Modal>;
}








