BEGIN;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS notes text NOT NULL DEFAULT '';
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS discount numeric(12,2) NOT NULL DEFAULT 0;
ALTER TABLE sales ADD COLUMN IF NOT EXISTS notes text NOT NULL DEFAULT '';
ALTER TABLE sales ADD COLUMN IF NOT EXISTS discount numeric(12,2) NOT NULL DEFAULT 0;
COMMIT;
