import { cache } from "react";
import { api, session } from "./client";
type Entity = { id: string;[key: string]: unknown };
export const str = (e: Entity, key: string, fallback = "") => String(e[key] ?? fallback);
const num = (e: Entity, key: string) => Number(e[key] ?? 0);
const day = (e: Entity, key = "createdAt") => str(e, key).slice(0, 10);
const nullable = (e: Entity, key: string) => e[key] ? String(e[key]) : null;
const status = (e: Entity, map: Record<string, string>) => map[str(e, "status")] || str(e, "status");
export const backendData = cache(async () => {
  const user = await session();
  const list = (path: string, permission: string) => user.permissions.includes(permission) ? api<Entity[]>(path) : Promise.resolve([] as Entity[]);
  const [clients, sellers, quotes, sales, products, inventory, receivables, payables, commissions, workOrders, pools, categories, users, suppliers] = await Promise.all([
    list("/customers", "CUSTOMER_VIEW"), list("/salespeople", "SALESPERSON_VIEW"), list("/quotes", "SALE_VIEW"), list("/sales", "SALE_VIEW"), list("/products", "PRODUCT_VIEW"), list("/inventory", "STOCK_VIEW"), list("/financial/receivables", "FINANCIAL_VIEW"), list("/financial/payables", "FINANCIAL_VIEW"), list("/commissions", "COMMISSION_VIEW"), list("/work-orders", "WORK_ORDER_VIEW"), list("/pools", "POOL_VIEW"), list("/product-categories", "PRODUCT_VIEW"), list("/users", "USER_VIEW"), list("/suppliers", "SUPPLIER_VIEW")
  ]);
  const [quoteDetails, saleDetails, histories] = await Promise.all([
    Promise.all(quotes.map(q => api<{ quote: Entity; items: Entity[] }>(`/quotes/${q.id}`))),
    Promise.all(sales.map(s => api<{ sale: Entity; items: Entity[]; costs: Entity[]; payments: Entity[] }>(`/sales/${s.id}`))),
    user.permissions.includes("STOCK_VIEW") ? Promise.all(inventory.map(p => api<Entity[]>(`/inventory/${str(p, "productId")}/history`))) : Promise.resolve([] as Entity[][])
  ]);
  const cust = clients.map(c => ({ id: c.id, name: str(c, "name"), phone: str(c, "phone"), email: str(c, "email"), document: str(c, "documentNumber"), address: str(c, "address"), city: str(c, "city"), state: str(c, "state"), notes: "", createdAt: day(c) }));
  const sell = sellers.map(s => ({ id: s.id, name: str(s, "name"), email: str(s, "email"), phone: str(s, "phone"), commissionPct: str(s, "defaultCommissionRate", "0"), monthlyGoal: str(s, "monthlyTarget", "0"), active: s.active !== false }));
  const quo = quotes.map(q => ({ id: q.id, number: q.id, customerId: str(q, "customerId"), salespersonId: nullable(q, "salespersonId"), project: str(q, "project", "Proposta"), notes: str(q, "notes"), discount: str(q, "discount", "0"), status: status(q, { DRAFT: "ORCAMENTO", SENT: "ORCAMENTO", NEGOTIATION: "NEGOCIACAO", APPROVED: "NEGOCIACAO", REJECTED: "CANCELADO", EXPIRED: "CANCELADO", CONVERTED: "FECHADO" }), total: str(q, "total", "0"), validUntil: nullable(q, "validUntil"), createdAt: day(q), convertedSaleId: nullable(q, "convertedSaleId") }));
  const sal = sales.map(s => ({ id: s.id, number: s.id, customerId: str(s, "customerId"), salespersonId: nullable(s, "salespersonId"), quoteId: nullable(s, "quoteId"), status: status(s, { COMPLETED: "FECHADA", CANCELLED: "CANCELADA", DRAFT: "NEGOCIACAO", NEGOTIATION: "NEGOCIACAO", APPROVED: "NEGOCIACAO" }), saleDate: day(s, "completedAt") || day(s), totalValue: str(s, "totalSale", "0"), totalCost: str(s, "totalCost", "0"), commission: str(s, "commissionAmount", "0"), profit: str(s, "profit", "0"), margin: str(s, "marginPercent", "0"), discount: str(s, "discount", "0"), notes: str(s, "notes"), project: str(s, "project"), paymentSummary: saleDetails.find(d => d.sale.id === s.id)?.payments.map(p => str(p, "paymentMethod")).filter((v, i, a) => a.indexOf(v) === i).join(" + ") || "A combinar" }));
  const its = saleDetails.flatMap(d => d.items.map(i => ({ id: i.id, saleId: d.sale.id, productId: nullable(i, "productId"), description: str(i, "description"), qty: num(i, "quantity"), unitPrice: str(i, "unitPrice", "0"), unitCost: str(i, "unitCost", "0") })));
  const qItems = quoteDetails.flatMap(d => d.items.map(i => ({ id: i.id, quoteId: d.quote.id, productId: nullable(i, "productId"), description: str(i, "description"), qty: num(i, "quantity"), unitPrice: str(i, "unitPrice", "0"), unitCost: str(i, "unitCost", "0") })));
  const costs = saleDetails.flatMap(d => [...d.costs.map(c => ({ id: c.id, saleId: d.sale.id, type: str(c, "type"), description: str(c, "description"), amount: str(c, "amount", "0") })), ...d.items.map(i => ({ id: `product-${i.id}`, saleId: d.sale.id, type: "PRODUCT", description: `Custo â€” ${str(i, "description")}`, amount: str(i, "totalCost", "0") }))]);
  const comms = commissions.map(c => ({ id: c.id, saleId: str(c, "saleId"), salespersonId: str(c, "salespersonId"), pct: str(c, "rate", "0"), amount: str(c, "amount", "0"), month: day(c).slice(0, 7), status: str(c, "status") === "PAID" ? "PAGA" : "PENDENTE" }));
  const now = new Date().toLocaleDateString("en-CA", { timeZone: "America/Cuiaba" });
  const recv = receivables.filter(r => str(r, "status") !== "CANCELLED").map(r => ({ id: r.id, saleId: str(r, "sourceType") === "SALE" ? nullable(r, "sourceId") : null, customerId: nullable(r, "customerId"), description: str(r, "description"), amount: str(r, "amount", "0"), method: str(r, "paymentMethod"), dueDate: day(r, "dueDate"), paidAt: nullable(r, "paidAt")?.slice(0, 10) || null, status: str(r, "status") === "PAID" ? "RECEBIDO" : day(r, "dueDate") < now ? "VENCIDO" : "PENDENTE" }));
  const pay = payables.filter(p => str(p, "status") !== "CANCELLED").map(p => ({ id: p.id, supplierId: nullable(p, "supplierId"), description: str(p, "description"), category: "Operacional", amount: str(p, "amount", "0"), dueDate: day(p, "dueDate"), paidAt: nullable(p, "paidAt")?.slice(0, 10) || null, status: str(p, "status") === "PAID" ? "PAGO" : day(p, "dueDate") < now ? "VENCIDO" : "PENDENTE" }));
  const prods = products.map(p => { const stock = inventory.find(s => str(s, "productId") === p.id); let details: Record<string, string> = {}; try { details = JSON.parse(str(p, "detailsJson", "{}")); } catch { } return { id: p.id, sku: str(p, "sku"), name: str(p, "name"), categoryId: nullable(p, "categoryId"), unit: str(p, "unit"), salePrice: str(p, "salePrice", "0"), avgCost: str(p, "costPrice", "0"), lastCost: str(p, "costPrice", "0"), stock: stock ? num(stock, "physical") : 0, reserved: stock ? num(stock, "reserved") : 0, minStock: num(p, "minimumStock"), values: { ...details, currentStock: String(stock ? num(stock, "physical") : 0), currentReserved: String(stock ? num(stock, "reserved") : 0), currentAvailable: String(stock ? num(stock, "available") : 0), sku: str(p, "sku"), barcode: str(p, "barcode"), name: str(p, "name"), description: str(p, "description"), categoryId: str(p, "categoryId"), brandId: str(p, "brandId"), supplierId: str(p, "supplierId"), warehouseId: str(p, "defaultWarehouseId"), defaultLocationId: str(p, "defaultLocationId"), defaultPositionId: str(p, "defaultPositionId"), productTypeId: str(p, "productTypeId"), unitId: str(p, "unitId"), taxUnitId: str(p, "taxUnitId"), purchaseUnitId: str(p, "purchaseUnitId"), manufacturerId: str(p, "manufacturerId"), modelId: str(p, "modelId"), materialId: str(p, "materialId"), finishId: str(p, "finishId"), initialCost: str(p, "costPrice", "0"), salePrice: str(p, "salePrice", "0"), minimumStock: str(p, "minimumStock", "0"), unit: str(p, "unit", "UN"), active: String(p.active !== false) } }; });
  const wos = workOrders.map(w => ({ id: w.id, number: w.id, customerId: str(w, "customerId"), saleId: null as string | null, type: str(w, "type"), technician: users.find(u => u.id === str(w, "assignedUserId")) ? str(users.find(u => u.id === str(w, "assignedUserId"))!, "name") : "NÃ£o atribuÃ­do", team: "", status: status(w, { SCHEDULED: "AGENDADA", IN_PROGRESS: "EXECUCAO", COMPLETED: "CONCLUIDA", CANCELLED: "CANCELADA" }), scheduledDate: day(w, "scheduledAt"), timeSlot: "", address: cust.find(c => c.id === str(w, "customerId"))?.address || "", poolModel: "", notes: str(w, "description"), createdAt: day(w) }));
  return {
    cust, sell, quo, sal, its, qItems, costs, comms, recv, pay, prods, wos,
    cats: categories.map(c => ({ id: c.id, name: str(c, "name") })),
    movs: histories.flat().map(m => ({ id: m.id, productId: str(m, "productId"), type: ({ ENTRY: "ENTRADA", EXIT: "SAIDA", RESERVATION: "RESERVA", RELEASE: "LIBERACAO", ADJUSTMENT: "AJUSTE", RETURN: "ENTRADA" } as Record<string, string>)[str(m, "type")] || str(m, "type"), quantity: num(m, "quantity"), reason: str(m, "notes"), reference: str(m, "referenceType"), createdBy: users.find(u => u.id === str(m, "createdBy"))?.name as string || "Equipe", createdAt: day(m) })),
    pools: pools.map(p => ({ id: p.id, name: str(p, "model"), sizeLabel: `${str(p, "lengthM")} Ã— ${str(p, "widthM")} Ã— ${str(p, "depthM")} m`, volumeLiters: num(p, "volumeLiters"), material: "NÃ£o informado", equipment: [str(p, "motor"), str(p, "filterModel")].filter(Boolean).join(" Â· "), warrantyMonths: 0, basePrice: "0", active: true, customerId: str(p, "customerId"), warrantyUntil: nullable(p, "warrantyUntil") })),
    users: users.map(u => ({ id: u.id, name: str(u, "name"), email: str(u, "email"), login: str(u, "email"), role: Array.isArray(u.roles) ? String(u.roles[0]) : "", createdAt: null as string | null, active: u.active !== false })),
    suppliers: suppliers.map(s => ({ id: s.id, name: str(s, "name"), contact: "", phone: str(s, "phone"), email: str(s, "email"), category: "", paymentTerms: "" }))
  };
});

