"use server";
import {api} from "@/lib/backend/client";
export type StockStructureOption={id:number;product_id?:number;code:string|null;name:string;site_id?:number|null;site_name?:string|null;site?:string;cidade?:string|null;uf?:string|null;description?:string|null;tipo?:string|null;parent_id?:number|null;path?:string;depth?:number;active?:boolean;storage_allowed?:boolean;picking_allowed?:boolean;blocked?:boolean;capacity?:number|null;notes?:string|null;allows_entry?:boolean;allows_exit?:boolean;allows_transfer?:boolean;physical?:number;reserved?:number;available?:number;in_transit?:number;product?:string;sku?:string;warehouse?:string;location?:string};
export async function listStockSites(){return api<StockStructureOption[]>("/inventory/structure/sites");}
export async function listStockWarehouses(siteId?:string){return api<StockStructureOption[]>(`/inventory/structure/warehouses${siteId?`?siteId=${siteId}`:""}`);}
export async function listStockLocations(warehouseId:string){return api<StockStructureOption[]>(`/inventory/structure/locations?warehouseId=${warehouseId}`);}
export async function createStockSite(code:string,name:string,details:Record<string,string>={}){return api("/inventory/structure/sites",{method:"POST",body:JSON.stringify({code,name,...details})});}
export async function createStockWarehouse(siteId:string,code:string,name:string,details:Record<string,string>={}){return api("/inventory/structure/warehouses",{method:"POST",body:JSON.stringify({siteId,code,name,...details})});}
export async function createStockLocation(warehouseId:string,code:string,name:string,details:Record<string,string>={}){return api("/inventory/structure/locations",{method:"POST",body:JSON.stringify({warehouseId,code,name,...details})});}
export async function updateStockSite(id:number,code:string,name:string,details:Record<string,string>={}){return api(`/inventory/structure/sites/${id}`,{method:"PUT",body:JSON.stringify({code,name,...details})});}
export async function updateStockWarehouse(id:number,siteId:string,code:string,name:string,details:Record<string,string>={}){return api(`/inventory/structure/warehouses/${id}`,{method:"PUT",body:JSON.stringify({siteId,code,name,...details})});}
export async function updateStockLocation(id:number,warehouseId:string,code:string,name:string,details:Record<string,string>={}){return api(`/inventory/structure/locations/${id}`,{method:"PUT",body:JSON.stringify({warehouseId,code,name,...details})});}
export async function listStockBalances(filters:{siteId?:string;warehouseId?:string;locationId?:string;product?:string;productId?:string}){const query=new URLSearchParams(Object.entries(filters).filter(([,v])=>v).map(([k,v])=>[k,String(v)]));return api<StockStructureOption[]>(`/inventory/structure/balances?${query}`);}
