package br.com.poolcontrol.inventory.controller;

import br.com.poolcontrol.shared.security.CurrentUserService;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.web.bind.annotation.*;
import java.math.BigDecimal;
import java.util.*;

@RestController @RequestMapping("/api/v1/inventory/addresses") @RequiredArgsConstructor
public class WarehouseAddressController {
 private final JdbcClient jdbc; private final CurrentUserService currentUser;
 private static final Map<String,String> TABLES=Map.of("building","predios","street","ruas","rack","estantes","bay","vaos","level","niveis","position","posicoes");
 private static final Map<String,String> PARENTS=Map.of("building","deposito_id","street","predio_id","rack","rua_id","bay","estante_id","level","vao_id","position","nivel_id");
 private static final Map<String,String> PREFIXES=Map.of("building","PRE","street","RUA","rack","EST","bay","VAO","level","NIV","position","POS");
 private String table(String kind){String value=TABLES.get(kind);if(value==null)throw new IllegalArgumentException("Tipo de endereço inválido.");return value;}
 @GetMapping("/tree") public List<Map<String,Object>> tree(@RequestParam Long warehouseId){return jdbc.sql("""
  SELECT id,code,name,tipo,parent_id,path,depth,active,capacity FROM (
   SELECT b.id,b.codigo code,b.nome name,'building' tipo,NULL::bigint parent_id,b.codigo::text path,0 depth,b.ativo active,NULL::numeric capacity FROM predios b WHERE b.empresa_id=:company AND b.deposito_id=:warehouse
   UNION ALL SELECT r.id,r.codigo,r.nome,'street',r.predio_id,concat_ws(' > ',b.codigo,r.codigo),1,r.ativo,NULL::numeric FROM ruas r JOIN predios b ON b.id=r.predio_id WHERE r.empresa_id=:company AND b.deposito_id=:warehouse
   UNION ALL SELECT e.id,e.codigo,e.nome,'rack',e.rua_id,concat_ws(' > ',b.codigo,r.codigo,e.codigo),2,e.ativo,NULL::numeric FROM estantes e JOIN ruas r ON r.id=e.rua_id JOIN predios b ON b.id=r.predio_id WHERE e.empresa_id=:company AND b.deposito_id=:warehouse
   UNION ALL SELECT v.id,v.codigo,v.nome,'bay',v.estante_id,concat_ws(' > ',b.codigo,r.codigo,e.codigo,v.codigo),3,v.ativo,NULL::numeric FROM vaos v JOIN estantes e ON e.id=v.estante_id JOIN ruas r ON r.id=e.rua_id JOIN predios b ON b.id=r.predio_id WHERE v.empresa_id=:company AND b.deposito_id=:warehouse
   UNION ALL SELECT n.id,n.codigo,n.nome,'level',n.vao_id,concat_ws(' > ',b.codigo,r.codigo,e.codigo,v.codigo,n.codigo),4,n.ativo,n.capacidade FROM niveis n JOIN vaos v ON v.id=n.vao_id JOIN estantes e ON e.id=v.estante_id JOIN ruas r ON r.id=e.rua_id JOIN predios b ON b.id=r.predio_id WHERE n.empresa_id=:company AND b.deposito_id=:warehouse
   UNION ALL SELECT p.id,p.codigo,p.nome,'position',p.nivel_id,concat_ws(' > ',b.codigo,r.codigo,e.codigo,v.codigo,n.codigo,p.codigo),5,p.ativo,p.capacidade FROM posicoes p JOIN niveis n ON n.id=p.nivel_id JOIN vaos v ON v.id=n.vao_id JOIN estantes e ON e.id=v.estante_id JOIN ruas r ON r.id=e.rua_id JOIN predios b ON b.id=r.predio_id WHERE p.empresa_id=:company AND b.deposito_id=:warehouse
  ) address_tree ORDER BY path
  """).param("company",currentUser.companyId()).param("warehouse",warehouseId).query().listOfRows();}
 @GetMapping("/{kind}") public List<Map<String,Object>> list(@PathVariable String kind,@RequestParam Long parentId){String sql="SELECT id,codigo code,nome name,descricao description,ativo active"+(kind.equals("level")||kind.equals("position")?",capacidade capacity":"")+" FROM "+table(kind)+" WHERE empresa_id=:company AND "+PARENTS.get(kind)+"=:parent AND ativo ORDER BY codigo";return jdbc.sql(sql).param("company",currentUser.companyId()).param("parent",parentId).query().listOfRows();}
 @GetMapping("/position/{id}/path") public Map<String,Object> path(@PathVariable Long id){return jdbc.sql("SELECT p.id position_id,n.id level_id,v.id bay_id,e.id rack_id,r.id street_id,b.id building_id,b.deposito_id warehouse_id,concat_ws('-',b.codigo,r.codigo,e.codigo,v.codigo,n.codigo,p.codigo) address FROM posicoes p JOIN niveis n ON n.id=p.nivel_id JOIN vaos v ON v.id=n.vao_id JOIN estantes e ON e.id=v.estante_id JOIN ruas r ON r.id=e.rua_id JOIN predios b ON b.id=r.predio_id WHERE p.id=:id AND p.empresa_id=:company").param("id",id).param("company",currentUser.companyId()).query().singleRow();}
 @PostMapping("/{kind}") public Map<String,Object> create(@PathVariable String kind,@RequestBody Map<String,Object>b){String table=table(kind);Long id=jdbc.sql("SELECT nextval('"+table+"_id_seq')").query(Long.class).single();String informed=String.valueOf(b.getOrDefault("code","")).trim();String code=informed.isBlank()?PREFIXES.get(kind)+"-"+String.format("%04d",id):informed.toUpperCase();String extra=kind.equals("level")?",capacidade":kind.equals("position")?",capacidade,permite_armazenagem,permite_picking,bloqueada":"";String values=kind.equals("level")?",:capacity":kind.equals("position")?",:capacity,:storage,:picking,:blocked":"";var q=jdbc.sql("INSERT INTO "+table+"(id,empresa_id,"+PARENTS.get(kind)+",codigo,nome,descricao,ativo"+extra+") VALUES(:id,:company,:parent,:code,:name,:description,true"+values+") RETURNING id,codigo code,nome name").param("id",id).param("company",currentUser.companyId()).param("parent",Long.valueOf(String.valueOf(b.get("parentId")))).param("code",code).param("name",b.get("name")).param("description",b.getOrDefault("description",""));if(kind.equals("level")||kind.equals("position"))q.param("capacity",number(b.get("capacity")));if(kind.equals("position"))q.param("storage",bool(b,"storage",true)).param("picking",bool(b,"picking",false)).param("blocked",bool(b,"blocked",false));return q.query().singleRow();}
 @PutMapping("/{kind}/{id}") public Map<String,Object> update(@PathVariable String kind,@PathVariable Long id,@RequestBody Map<String,Object>b){String extras=kind.equals("level")?",capacidade=:capacity":kind.equals("position")?",capacidade=:capacity,permite_armazenagem=:storage,permite_picking=:picking,bloqueada=:blocked":"";var q=jdbc.sql("UPDATE "+table(kind)+" SET "+PARENTS.get(kind)+"=:parent,codigo=upper(trim(:code)),nome=trim(:name),descricao=:description"+extras+" WHERE id=:id AND empresa_id=:company RETURNING id,codigo code,nome name").param("id",id).param("company",currentUser.companyId()).param("parent",Long.valueOf(String.valueOf(b.get("parentId")))).param("code",b.get("code")).param("name",b.get("name")).param("description",b.getOrDefault("description",""));if(kind.equals("level")||kind.equals("position"))q.param("capacity",number(b.get("capacity")));if(kind.equals("position"))q.param("storage",bool(b,"storage",true)).param("picking",bool(b,"picking",false)).param("blocked",bool(b,"blocked",false));return q.query().singleRow();}
 private BigDecimal number(Object value){if(value==null||String.valueOf(value).isBlank())return null;return new BigDecimal(String.valueOf(value));}
 private boolean bool(Map<String,Object>b,String key,boolean fallback){return b.get(key)==null?fallback:Boolean.parseBoolean(String.valueOf(b.get(key)));}
}
